apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-print
  template:
    metadata:
      labels:
        app: python-print
    spec:
      containers:
        - name: python-cpontainer
          image: alex4386/hello-pod:latest

