apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-print
  template:
    metadata:
      labels:
        app: python-print
    spec:
      containers:
        - name: python-container
          image: alex4386/201935044:v1

